package pl.peth.datacollector

object Constants {

    const val ACTION_START_OR_RESUME_SERVICE = "ACTION_START_OR_RESUME_SERVICE"
    const val ACTION_PAUSE_SERVICE = "ACTION_PAUSE_SERVICE"
    const val ACTION_STOP_SERVICE = "ACTION_STOP_SERVICE"
    const val ACTION_SHOW_POSITION_FRAGMENT = "ACTION_SHOW_POSITION_FRAGMENT"

    const val LOCATION_UPDATE_INTERVAL = 1000L
    const val FASTEST_LOCATION_UPDATE_INTERVAL = 500L

    const val NOTIFICATION_CHANNEL_ID = "tracking_channel"
    const val NOTIFICATION_CHANNEL_NAME = "Tracking"
    const val NOTIFICATION_ID = 1
}
